version: '3.4'
services:
  database:
    container_name: 'shoprate_db'
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: shopratedb
