export const enum ExceptionCodeName {
  INVALID_USER_ROLE_KEY = 'INVALID_USER_ROLE_KEY',
  INVALID_ENVIRONMENT_VARIABLE = 'INVALID_ENVIRONMENT_VARIABLE',
  USER_EMAIL_CONFLICT = 'USER_EMAIL_CONFLICT',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
}
